name: Workflow con Contenedor

on:
  push:
    branches:
      - test_1   
jobs:
  run-in-container:
    runs-on: ubuntu-latest
    container:
      image: python:3.10   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ejecutar acci贸n dentro del contenedor
        run: |
          echo "Impresi贸n 1 desde contenedor"
          echo "Impresi贸n 2 desde contenedor"
          echo "Impresi贸n 3 desde contenedor"
          python --version   # Ejemplo: usar Python dentro del contenedor
